export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_DROPDOWN = "TOGGLE_CART_DROPDOWN";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const GET_SECTIONS = "GET_SECTIONS";
//export const UPDATE_COLLECTION  = "UPDATE_COLLECTION";

export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILED = "FETCH_COLLECTIONS_FAILED";