export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_DROPDOWN = "TOGGLE_CART_DROPDOWN";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const GET_SECTIONS = "GET_SECTIONS";
//export const UPDATE_COLLECTION  = "UPDATE_COLLECTION";

export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILED = "FETCH_COLLECTIONS_FAILED";


export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START";
export const EMAIL_SIGNIN_START = "EMAIL_SIGNIN_START";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FALIED";

export const CHECK_USER_SESSION = "CHECK_USER_SESSION";

export const SIGNOUT_START = "SIGNOUT_START";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILED = "SIGNOUT_FALIED";

export const CLEAR_CART = "CLEAR_CART";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FALIED";
